### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by madfff** [csm9493/FBI-Denoiser#2]
Could you provide datasets (such as train_SIDD_25000_2.hdf5, train_DND_25000_2.hdf5 and so on) or release the data-processing code?

**Comment by csm9493** [comment]
Sorry for the late reply.

I just uploaded the new version of our code.
We could not upload whole training datasets because it is too big to upload my google drive.
However, I added the data-processing code for generating synthetic noise datasets in './data/'. I recommend to check it to solve your problem.

if you have any questions, places let me know.

Sungmin.
